FISH-6392:improving memory for alpn negotiator maps
payara/patched-src-grizzly-npn pull request #5
Opened 2022-07-12 23:44 UTC by breakponchito

Improving ConcurrentHashMaps using String key instead of SSLEngine instance

2022-07-14 14:38 UTC, luiseufrasio requested changes

2022-07-14 14:38 UTC, luiseufrasio commented on api/src/main/java/org/glassfish/grizzly/npn/NegotiationSupport.java
> +        return null;
Is it possible to return an empty String instead of null?

2022-07-14 15:08 UTC, breakponchito commented on api/src/main/java/org/glassfish/grizzly/npn/NegotiationSupport.java
> +        return null;
If I leave an empty String then the ConcurrentHashMap is going to try to add an empty String as a key, that is not the ideal behaviour, for now how the ConcurrentHashMap is not accepting either null keys and null values so basically the ConcurrentHashMap is going to throw the nullpointer exception when the key or value is null. That is the default behaviour for the implementation

2022-07-22 16:36 UTC, Pandrex247 approved these changes

2022-07-22 18:32 UTC, luiseufrasio approved these changes
LGTM

2022-07-22 18:33 UTC, merged