Fish-6392: improve memory for alpn negotiator maps payara6
payara/patched-src-grizzly-npn pull request #7
Opened 2022-07-14 01:23 UTC by breakponchito

Improving ConcurrentHashMaps using String key instead of SSLEngine instance

Tests
Tested on local environment by calling a rest service using https on Payara 6 Server
Build Environment:
Windows 11, Oracle JDK 8 u 251, Maven 3.8.3

2022-07-22 16:39 UTC, Pandrex247 reviewed
Are the JDK8 compatible changes necessary?

2022-07-22 22:20 UTC, breakponchito commented
> 

after downloading the branch 2.0.0.payara-maintanance into our patched project I saw that was necessary to consider use an older Oracle JDK 8 to build the project. That was very strange and after trying several version of oracle jdk 8, 9 and 10 I saw that the way to do it was to get the compatibility changes from the 1.9.payara-maintenance branch and then build the project with the Oracle JDK 1.8.0 u 251. Then when trying this dependency with Payara6 compiled with JDK 11 I didn't saw any issues when executing an application either when using the https enabling the use of the grizzly-npn dependency. If you prefer we can wait to merge this change for Payara6. The report came from the use of  Payara Enterprise version 5.29 and those changes were merged already and the dependency was upgraded at nexus

2022-07-26 08:56 UTC, Pandrex247 approved these changes

2022-07-26 10:31 UTC, Pandrex247 requested changes

2022-07-26 10:31 UTC, Pandrex247 commented on api/pom.xml
> +        <version>2.0.2-SNAPSHOT</version>
This isn't aligned with our usual versioning strategy.
Should be `2.0.0.payara-p1` (followed by `2.0.0.payara-p2-SNAPSHOT`) - we shouldn't be touching the "actual" version so as to not collide with upstream if they do a 2.0.1 release.

2022-07-26 10:35 UTC, Pandrex247 commented on api/pom.xml
> +        <version>2.0.2-SNAPSHOT</version>
I've deleted the 2.0.1 version uploaded to payara-artifacts, as it's incorrect.

2022-08-01 11:04 UTC, Pandrex247 commented
Built and uploaded 2.0.0.payara-p1 tag

2022-08-01 12:51 UTC, Pandrex247 approved these changes

2022-08-01 12:51 UTC, merged